#!/bin/bash
# Propagates the live session's detected keyboard layout into the target,
# so the installed system matches what the user had during install.
setxkbmap -query | awk '/layout/{ print $2 }' > /dev/shm/fixconkeys-layout
cp /usr/libexec/fixconkeys-part2 ${1}/usr/libexec/fixconkeys-part2
